import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import MainView from '@/components/MainView'
import Header from '@/components/Header'
import MainSection from '@/components/MainSection'

const inter = Inter({ subsets: ['latin'] }) 


export default function Home() {
  return (
    <div>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-4RD70P32GJ"></Script>
      <Script id="google-analitycs"> {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-4RD70P32GJ');
      `}</Script>
      <Head>
        <title>Healthy Living</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <MainView />
        <MainSection />
      </main>
    </div>
  )
}
